package entities;

// Generated May 21, 2016 10:13:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hanghoa generated by hbm2java
 */
@Entity
@Table(name = "Hanghoa", catalog = "Banhang")
public class Hanghoa implements java.io.Serializable {

	private int mahang;
	private Loaisanpham loaisanpham;
	private String tenhang;
	private String dvt;
	private String mota;
	private String thongsokt;
	private Integer giaban;
	private String hinhanh;
	private Integer solanxem;
	private String mau;
	private String size;
	private String ghichu;
	private Set<Tonkho> tonkhos = new HashSet<Tonkho>(0);

	public Hanghoa() {
	}

	public Hanghoa(int mahang) {
		this.mahang = mahang;
	}

	public Hanghoa(int mahang, Loaisanpham loaisanpham, String tenhang,
			String dvt, String mota, String thongsokt, Integer giaban,
			String hinhanh, Integer solanxem, String mau, String size,
			String ghichu, Set<Tonkho> tonkhos) {
		this.mahang = mahang;
		this.loaisanpham = loaisanpham;
		this.tenhang = tenhang;
		this.dvt = dvt;
		this.mota = mota;
		this.thongsokt = thongsokt;
		this.giaban = giaban;
		this.hinhanh = hinhanh;
		this.solanxem = solanxem;
		this.mau = mau;
		this.size = size;
		this.ghichu = ghichu;
		this.tonkhos = tonkhos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Mahang", unique = true, nullable = false)
	public int getMahang() {
		return this.mahang;
	}

	public void setMahang(int mahang) {
		this.mahang = mahang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Maloai")
	public Loaisanpham getLoaisanpham() {
		return this.loaisanpham;
	}

	public void setLoaisanpham(Loaisanpham loaisanpham) {
		this.loaisanpham = loaisanpham;
	}

	@Column(name = "Tenhang", length = 50)
	public String getTenhang() {
		return this.tenhang;
	}

	public void setTenhang(String tenhang) {
		this.tenhang = tenhang;
	}

	@Column(name = "Dvt", length = 50)
	public String getDvt() {
		return this.dvt;
	}

	public void setDvt(String dvt) {
		this.dvt = dvt;
	}

	@Column(name = "Mota")
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "Thongsokt")
	public String getThongsokt() {
		return this.thongsokt;
	}

	public void setThongsokt(String thongsokt) {
		this.thongsokt = thongsokt;
	}

	@Column(name = "Giaban")
	public Integer getGiaban() {
		return this.giaban;
	}

	public void setGiaban(Integer giaban) {
		this.giaban = giaban;
	}

	@Column(name = "Hinhanh", length = 50)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "Solanxem")
	public Integer getSolanxem() {
		return this.solanxem;
	}

	public void setSolanxem(Integer solanxem) {
		this.solanxem = solanxem;
	}

	@Column(name = "Mau", length = 50)
	public String getMau() {
		return this.mau;
	}

	public void setMau(String mau) {
		this.mau = mau;
	}

	@Column(name = "Size", length = 50)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "Ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<Tonkho> getTonkhos() {
		return this.tonkhos;
	}

	public void setTonkhos(Set<Tonkho> tonkhos) {
		this.tonkhos = tonkhos;
	}

}
