package entities;

// Generated May 21, 2016 10:13:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kho generated by hbm2java
 */
@Entity
@Table(name = "Kho", catalog = "Banhang")
public class Kho implements java.io.Serializable {

	private int makho;
	private String tenkho;
	private String diachi;
	private String ghichu;
	private Set<Tonkho> tonkhos = new HashSet<Tonkho>(0);

	public Kho() {
	}

	public Kho(int makho) {
		this.makho = makho;
	}

	public Kho(int makho, String tenkho, String diachi, String ghichu,
			Set<Tonkho> tonkhos) {
		this.makho = makho;
		this.tenkho = tenkho;
		this.diachi = diachi;
		this.ghichu = ghichu;
		this.tonkhos = tonkhos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Makho", unique = true, nullable = false)
	public int getMakho() {
		return this.makho;
	}

	public void setMakho(int makho) {
		this.makho = makho;
	}

	@Column(name = "tenkho", length = 50)
	public String getTenkho() {
		return this.tenkho;
	}

	public void setTenkho(String tenkho) {
		this.tenkho = tenkho;
	}

	@Column(name = "Diachi")
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "Ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kho")
	public Set<Tonkho> getTonkhos() {
		return this.tonkhos;
	}

	public void setTonkhos(Set<Tonkho> tonkhos) {
		this.tonkhos = tonkhos;
	}

}
