package entities;

// Generated May 21, 2016 10:13:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaisanpham generated by hbm2java
 */
@Entity
@Table(name = "Loaisanpham", catalog = "Banhang")
public class Loaisanpham implements java.io.Serializable {

	private int maloai;
	private Sanpham sanpham;
	private String tenloai;
	private String ghichu;
	private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);

	public Loaisanpham() {
	}

	public Loaisanpham(int maloai, Sanpham sanpham) {
		this.maloai = maloai;
		this.sanpham = sanpham;
	}

	public Loaisanpham(int maloai, Sanpham sanpham, String tenloai,
			String ghichu, Set<Hanghoa> hanghoas) {
		this.maloai = maloai;
		this.sanpham = sanpham;
		this.tenloai = tenloai;
		this.ghichu = ghichu;
		this.hanghoas = hanghoas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Maloai", unique = true, nullable = false)
	public int getMaloai() {
		return this.maloai;
	}

	public void setMaloai(int maloai) {
		this.maloai = maloai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Masp", nullable = false)
	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	@Column(name = "Tenloai", length = 50)
	public String getTenloai() {
		return this.tenloai;
	}

	public void setTenloai(String tenloai) {
		this.tenloai = tenloai;
	}

	@Column(name = "Ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaisanpham")
	public Set<Hanghoa> getHanghoas() {
		return this.hanghoas;
	}

	public void setHanghoas(Set<Hanghoa> hanghoas) {
		this.hanghoas = hanghoas;
	}
	
	public int sohang(){
		return this.getHanghoas().size();
	}

}
