package entities;

// Generated May 21, 2016 10:13:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name = "Sanpham", catalog = "Banhang")
public class Sanpham implements java.io.Serializable {

	private int masp;
	private String tensp;
	private String ghichu;
	private Set<Loaisanpham> loaisanphams = new HashSet<Loaisanpham>(0);

	public Sanpham() {
	}

	public Sanpham(int masp) {
		this.masp = masp;
	}

	public Sanpham(int masp, String tensp, String ghichu,
			Set<Loaisanpham> loaisanphams) {
		this.masp = masp;
		this.tensp = tensp;
		this.ghichu = ghichu;
		this.loaisanphams = loaisanphams;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Masp", unique = true, nullable = false)
	public int getMasp() {
		return this.masp;
	}

	public void setMasp(int masp) {
		this.masp = masp;
	}

	@Column(name = "Tensp", length = 50)
	public String getTensp() {
		return this.tensp;
	}

	public void setTensp(String tensp) {
		this.tensp = tensp;
	}

	@Column(name = "Ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public Set<Loaisanpham> getLoaisanphams() {
		return this.loaisanphams;
	}

	public void setLoaisanphams(Set<Loaisanpham> loaisanphams) {
		this.loaisanphams = loaisanphams;
	}
	
	public int sohanghoa(){
		List<Loaisanpham> dsl = new ArrayList<Loaisanpham>(this.getLoaisanphams());
		int tong = 0;
		for (Loaisanpham lsp: dsl){
			tong = tong + lsp.getHanghoas().size();
		}
		return tong;
	}

}
